logging:
  level: 
    '[org.springframework.security]': DEBUG

server:
  port: 8082

spring:
  thymeleaf:
    cache: false
   
  security:    oauth2:      resourceserver:        jwt:          jwk-set-uri: http://localhost:8080/auth/realms/appsdevelopers/protocol/openid-connect/certs
         # issuer-uri: http://localhost:8080/auth/realms/appsdevelopers
    
#  ssl:
#    key-store-password: 
#    key-store: classpath:mykeystore.p12
#    key-store-type: PKCS12
#    key-alias:  